apiVersion: v1
kind: Service
metadata: 
    name: ftps-server
spec:
    type: LoadBalancer
    selector:
        app: ftps-server
    ports:
        - protocol: TCP
          port: 21
          targetPort: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ftps-server
    labels:
        app: ftps-server
spec:
    replicas: 1
    selector: 
        matchLabels:
            app: ftps-server
    template:
        metadata:
            labels:
                app: ftps-server
        spec:
            containers:
                - name: ftps-server
                  image: ftps-server:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 21
                  volumeMounts:
                      - name: telegraf-conf
                        mountPath: /etc/telegraf.conf
                        subPath: telegraf.conf
            volumes:
                - name: telegraf-conf
                  configMap:
                      name: telegraf-conf

