apiVersion: v1
kind: Service
metadata: 
    name: grafana-svc
spec:
    type: LoadBalancer
    selector:
        app: grafana
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana
    labels:
        app: grafana
spec:
    replicas: 1
    selector: 
        matchLabels:
            app: grafana
    template:
        metadata:
            labels:
                app: grafana
        spec:
            containers:
                - name: grafana
                  image: grafana:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3000
                  volumeMounts:
                      - name: ssl-certs
                        mountPath: /usr/local/share/ca-certificates/
                        readOnly: true
                      - name: telegraf-conf
                        mountPath: /etc/telegraf/
            volumes:
                - name: ssl-certs
                  secret:
                      secretName: ssl-cert
                - name: telegraf-conf
                  configMap:
                        name: telegraf-conf
