apiVersion: v1
kind: Secret
metadata:
    name: influx-credentials
type: Opaque
data:
    influx-admin-passwd: cGFzc3dk 
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb-svc
    labels:
        app: influxdb
spec:
    ports:
        - port: 8086
          targetPort: 8086
          protocol: TCP
    selector:
        app: influxdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: influxdb-volume
    labels:
        type: local
        volume-svc: influxdb
spec:
    storageClassName: manual
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: influxdb-volume-claim
    labels:
        app: influxdb
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 400Mi
    selector:
        matchLabels:
            type: local
            volume-svc: influxdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: influxdb
    labels:
        app: influxdb
spec:
    selector:
        matchLabels: 
            app: influxdb
    replicas: 1  
    template:
        metadata:
            labels:
                app: influxdb
        spec:
            containers:
                - name: influxdb
                  image: influxdb:latest
                  imagePullPolicy: Never
                  ports:
                      - protocol: TCP
                        containerPort: 8086
                  volumeMounts:
                      - name: influxdb-volume
                        mountPath: /var/lib/influxdb
                      - name: ssl-certs
                        mountPath: /usr/local/share/ca-certificates/
                        readOnly: true
                  env:
                      - name: TELEGRAF_PASSWD
                        valueFrom:
                            secretKeyRef:
                                name: telegraf-secrets
                                key: telegraf-passwd
                      - name: ADMIN_PASSWD
                        valueFrom:
                            secretKeyRef:
                                name: influx-credentials
                                key: influx-admin-passwd
            volumes:
                - name: ssl-certs
                  secret:
                      secretName: ssl-cert
                - name: influxdb-volume
                  persistentVolumeClaim:
                      claimName: influxdb-volume-claim
