apiVersion: v1
kind: Service
metadata:
    name: influxdb
    labels:
        app: influxdb
spec:
    ports:
        - port: 8086
          targetPort: 8086
          protocol: TCP
    selector:
        app: influxdb
    clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: influxdb
    labels:
        app: influxdb
spec:
    serviceName: influxdb
    selector:
        matchLabels: 
            app: influxdb
    replicas: 1 # tmp
    template:
        metadata:
            labels:
                app: influxdb
        spec:
            containers:
                - name: influxdb
                  image: influxdb
                  imagePullPolicy: Never
                  ports:
                      - protocol: TCP
                        containerPort: 8086
                  volumeMounts:
                      - name: influxdb-volume
                        mountPath: /var/lib/influxdb ## to change
    volumeClaimTemplates:
        - metadata:
                name: influxdb-volume
          spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 2Gi

