apiVersion: v1
kind: Service
metadata:
    name: influxdb-svc
    labels:
        app: influxdb
spec:
    ports:
        - port: 8086
          targetPort: 8086
          protocol: TCP
    selector:
        app: influxdb
    clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: influxdb-volume
    labels:
        type: local
        volume-svc: influxdb
spec:
    storageClassName: manual
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/var/lib/influxbd"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: influxdb-volume-claim
    labels:
        app: influxdb
spec:
    storageClassName: manial
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 400Mi
    selector:
        matchLabels:
            type: local
            volume-svc: influxdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: influxdb
    labels:
        app: influxdb
spec:
    serviceName: influxdb
    selector:
        matchLabels: 
            app: influxdb
    replicas: 1  
    template:
        metadata:
            labels:
                app: influxdb
        spec:
            containers:
                - name: influxdb
                  image: influxdb
                  imagePullPolicy: Never
                  ports:
                      - protocol: TCP
                        containerPort: 8086
                  volumeMounts:
                      - name: influxdb-volume
                        mountPath: /var/lib/influxdb ## to change??
                      - name: ssl-certs
                        mountPath: /etc/ssl
                        readOnly: true
            volumes:
                - name: ssl-certs
                  secret:
                      secretName: ssl-cert
                - name: influxdb-volume
                  persistentVolumeClaim:
                      claimName: influxdb-volume-claim
                           ## this needs env vars
