apiVersion: v1
kind: ConfigMap
metadata:
        namespace: metallb-system
        name: config
data:
        config: |
                address-pools:
                - name: default
                  protocol: layer2
                  addresses:
                  - 192.168.99.10/25
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
    - name: nginx-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: nginx-https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: wordpress
      protocol: TCP
      port: 5050
      targetPort: 5050
    - name: phpmyadmin
      protocol: TCP
      port: 5000
      targetPort: 5000
