apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
        app: mysql-service
spec:
    ports:
        - port: 3306
          targetPort: 3306
          protocol: TCP
    selector:
    clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    hola: hola
    type: local
spec:
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    serviceName: mysql-service
    selector:
        matchLabels: 
            app: mysql
    replicas: 1 # tmp
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql
                  imagePullPolicy: Never
                  ports:
                      - protocol: TCP
                        containerPort: 3306
                  volumeMounts:
                      - name: mysql-volume
                        mountPath: /var/lib/mysql
    volumeClaimTemplates:
        - metadata:
              name: mysql-volume
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                    requests:
                          storage: 600Mi
              selector:
                  matchLabels:
                      hola: hola

