apiVersion: v1
kind: Secret
metadata:
    name: mysql-credentials
type: Opaque
data:
    database: d3BfZGF0YWJhc2UK
    username: dXNlcgo=
    password: cGFzc3dkCg==
    root-password: cm9vdHBhc3N3ZAo=
