apiVersion: v1
kind: Service
metadata:
    name: mysql
spec:
    clusterIP: None
    selector:
        app: mysql
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql
spec:
    replicas: 1
    serviceName: mysql
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql-service
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3306
                        protocol: TCP
                  env:
                      - name: ROOT_PASSWD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-credentials
                                key: root-password
                      - name: WP_DATABASE
                        valueFrom:
                            secretKeyRef:
                                name: WP_DATABASE
                                key: database
                      - name: WP_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mysql-credentials
                                key: username
                      - name: WP_PASSWD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-credentials
                                key: password
