apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-volume
    labels:
        type: local
        volume-svc: mysql
spec:
    storageClassName: manual
    capacity: 
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/var/lib/mysql"
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-svc
    labels:
        app: mysql-svc
spec:
    ports:
        - port: 3306
          targetPort: 3306
          protocol: TCP
    selector:
        app: mysql
    clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    serviceName: mysql-svc
    selector:
        matchLabels: 
            app: mysql
    replicas: 1 # tmp
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql
                  imagePullPolicy: Never
                  ports:
                      - protocol: TCP
                        containerPort: 3306
                  volumeMounts:
                      - name: mysql-volume-claim
                        mountPath: /var/lib/mysql
    volumeClaimTemplates:
        - metadata:
                name: mysql-volume-claim
          spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 1Gi
                        storageClassName: manual
                selector:
                    matchLabels:
                        type: local
                        volume-svc: mysql
