apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    ports:
        - port: 3306
          targetPort: 3306
          protocol: TCP
    selector:
        app: mysql
    clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    serviceName: mysql-service
    selector:
        matchLabels: 
            app: mysql
    replicas: 1 # tmp
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql
                  imagePullPolicy: Never
                  ports:
                      - protocol: TCP
                        containerPort: 3306
                  volumeMounts:
                      - name: mysql-volume
                        mountPath: /var/lib/mysql
    volumeClaimTemplates:
        - metadata:
                name: mysql-volume
          spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 2Gi

