apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    type:  NodePort
    selector:
        app: nginx
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30001
        - name: https
          protocol: TCP
          port: 443
          targetPort: 443
          nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    labels:
        app: nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
             containers:
               - name: nginx
                 image: nginx-service
                 imagePullPolicy: Never
                 ports:
                     - name: http
                       protocol: TCP
                       containerPort: 80
                     - name: https
                       protocol: TCP
                       containerPort: 443
