apiVersion: v1
kind: Service
metadata:
        name: nginx
spec:
        type: LoadBalancer
        selector:
                app: nginx
        ports:
                - name: http
                  protocol: TCP
                  port: 80
                  targetPort: 80
                - name: https
                  protocol: TCP
                  port: 443
                  targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx
        labels:
                app: nginx
spec:
        replicas: 2 ## tmp para cont. debug
        selector:
                matchLabels:
                        app: nginx
        template:
                metadata:
                        labels:
                                app: nginx
                spec:
                        containers:
                                - name: nginx
                                  image: nginx
                                  imagePullPolicy: Never
                                  ports:
                                          - containerPort: 80
                                            containerPort: 443
                                  volumeMounts:
                                    - name: ssl-certs
                                      mountPath: /etc/ssl/
                                      readOnly: true
                        volumes:
                          - name: ssl-certs
                            secret:
                                secretName: ssl-cert
