apiVersion: v1
kind: Secret
metadata:
    name: pma-credentials
type: Opaque
data:
    pma_user: cG1hX3VzZXIK
    pma_passwd: cG1hX3Bhc3N3ZAo=
---
apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-svc
spec:
    type: LoadBalancer
    selector:
        app: phpmyadmin
    ports:
        - name: http
          protocol: TCP
          port: 5000
          targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpmyadmin
    labels:
        app: phpmyadmin
spec:
    replicas: 1 ## !!
    selector:
        matchLabels:
            app: phpmyadmin
    template:
        metadata:
            labels:
                app: phpmyadmin
        spec:
             containers:
                 - name: phpmyadmin
                   image: phpmyadmin:latest
                   imagePullPolicy: Never
                   ports:
                       - containerPort: 80
                   volumeMounts:
                       - name: telegraf-conf
                         mountPath: /etc/telegraf/
                   env:
                       - name: PMA_USER
                         valueFrom:
                             secretKeyRef:
                                 name: pma-credentials
                                 key: pma_user
                       - name: PMA_PASSWD
                         valueFrom:
                             secretKeyRef:
                                 name: pma-credentials
                                 key: pma_passwd
             volumes:
                 - name: telegraf-conf
                   configMap:
                       name: telegraf-conf
