apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-svc
spec:
    type: LoadBalancer
    selector:
        app: phpmyadmin
    ports:
        - name: http
          protocol: TCP
          port: 5000
          targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpmyadmin
    labels:
        app: phpmyadmin
spec:
    replicas: 1 ## !!
    selector:
        matchLabels:
            app: phpmyadmin
    template:
        metadata:
            labels:
                app: phpmyadmin
        spec:
             containers:
                 - name: phpmyadmin
                   image: phpmyadmin:latest
                   imagePullPolicy: Never
                   ports:
                       - containerPort: 80
                   volumeMounts:
                       - name: telegraf-conf
                         mountPath: /etc/telegraf/
                         readOnly: true
             volumes:
                 - name: telegraf-conf
                   configMap:
                       name: telegraf-conf
