apiVersion: v1
kind: Secret
metadata:
    name: telegraf-secrets
type: Opaque
data:
    telegraf-db: dGVsZWdyYWY=
    telegraf-usr: dGVsZWdyYWY=
    telegraf-passwd: dGVsZWdyYWZwYXNzd2Q=
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: telegraf-conf
data:
    telegraf.conf: |+
        [global_tags]
        [agent]
          interval = "10s"
          round_interval = true
          metric_batch_size = 1000
          metric_buffer_limit = 10000
          collection_jitter = "0s"
          flush_interval = "10s"
          flush_jitter = "0s"
          precision = ""
          hostname = ""
          omit_hostname = false
        [[outputs.influxdb]]
          urls = ["https://influxdb-svc.default.svc.cluster.local:8086"]
          database = ""
          username = "telegraf"
          password = "telegrafpasswd"
          insecure_skip_verify = true
        [[inputs.cpu]]
          percpu = true
          totalcpu = true
          collect_cpu_time = false
          report_active = false
        [[inputs.mem]]
