apiServer: v1
kind: Service
metadata:
    name: wordpress
spec:
    selector:
        app: wordpress
    ports:
        - protocol: TCP
          port: 5050
          targetPort: 5050
#   clusterip: none
---
apiVersion: v1
kind: Deployment
metadata:
    name: wordpress
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wordpress
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
                - name: wordpress
                  image: wordpress-service
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 5050
                        protocol: TCP











### wp == statefulset??? ##
