apiVersion: v1
kind: Service
metadata:
        name: wordpress-service
        labels:
            app: wordpress-service
spec:
        selector:
                app: wordpress
        ports:
                - protocol: TCP
                  port: 5050
                  targetPort: 80
        selector:
                app: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volume-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: wordpress
spec:
        selector:
            matchLabels:
                app: wordpress
        replicas: 1 ## tmp
        template:
            metadata:
                labels: 
                    app: wordpress
            spec:
                containers:
                    - name: wordpress
                      image: wordpress
                      imagePullPolicy: Never
                      ports:
                          - protocol: TCP
                            containerPort: 80
                            containerPort: 443
                      volumeMounts:
                          - name: www
                            mountPath: /var/www
                volumes:
                     - name: www
                       persistentVolumeClaim: 
                            claimName: wordpress-volume-claim

