apiVersion: v1
kind: Secret
metadata:
    name: wp-credentials
type: Opaque
data:
    db_name: d3BfZGF0YWJhc2UK
    db_user: d3BfYWRtaW4K
    db_password: d3BfcGFzc3dkCg==
---
apiVersion: v1
kind: Service
metadata:
        name: wordpress
        labels:
            app: wordpress
spec:
        type: LoadBalancer
        selector:
                app: wordpress
        ports:
                - protocol: TCP
                  port: 5050
                  targetPort: 80
        selector:
                app: wordpress
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: wordpress-volume
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/var/www/html/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volume-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: wordpress
        labels:
            app: wordpress
spec:
        selector:
            matchLabels:
                app: wordpress
        replicas: 1 ## tmp
        template:
            metadata:
                labels: 
                    app: wordpress
            spec:
                containers:
                    - name: wordpress
                      image: wordpress
                      imagePullPolicy: Never
                      ports:
                          - protocol: TCP
                            containerPort: 80
                      volumeMounts:
                          - name: www
                            mountPath: /var/www/html
                      env:
                          - name: DB_NAME
                            valueFrom:
                                secretKeyRef:
                                    name: wp-credentials
                                    key: db_name
                          - name: DB_USER
                            valueFrom:
                                secretKeyRef:
                                    name: wp-credentials
                                    key: db_user
                          - name: DB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: wp-credentials
                                    key: db_password

                volumes:
                     - name: www
                       persistentVolumeClaim: 
                            claimName: wordpress-volume-claim

