apiVersion: v1
kind: Service
metadata:
        name: wordpress-service
specs:
        selector:
                app: wordpress
        ports:
                - protocol: TCP
                  port: 5050
                  targetPort: 5050  ## seguro?????
                  ## 5050 para acceder al servicio, 80/443 para acceder al contenedor (sigue siendo nginx)`:w
                  #
