apiVersion: v1
kind: Secret
metadata:
    name: wp-credentials
type: Opaque
data:
    db_name: d3BfZGF0YWJhc2UK
    wp_admin: d3BfYWRtaW4K
    wp_passwd: d3BfcGFzc3dkCg==
---
apiVersion: v1
kind: Service
metadata:
        name: wordpress-svc
        labels:
            app: wordpress
spec:
        type: LoadBalancer
        selector:
                app: wordpress
        ports:
                - protocol: TCP
                  port: 5050
                  targetPort: 5050
        selector:
                app: wordpress
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: wordpress-volume
    labels:
        type: local
        volume-svc: wordpress
spec:
    storageClassName: manual
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/wp/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volume-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:    
    matchLabels:
      type: local
      volume-svc: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: wordpress
        labels:
            app: wordpress
spec:
        selector:
            matchLabels:
                app: wordpress
        replicas: 1 
        template:
            metadata:
                labels: 
                    app: wordpress
            spec:
                containers:
                    - name: wordpress
                      image: wordpress:latest
                      imagePullPolicy: Never
                      ports:
                          - protocol: TCP
                            containerPort: 5050 
                      volumeMounts:
                          - name: www
                            mountPath: /var/www/localhost/htdocs
                          - name: telegraf-conf
                            mountPath: /etc/telegraf/
                      env:
                          - name: DB_NAME
                            valueFrom:
                                secretKeyRef:
                                    name: wp-credentials
                                    key: db_name
                          - name: DB_USER
                            valueFrom:
                                secretKeyRef:
                                    name: wp-credentials
                                    key: wp_admin
                          - name: DB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: wp-credentials
                                    key: wp_passwd

                volumes:
                     - name: www
                       persistentVolumeClaim: 
                            claimName: wordpress-volume-claim
                     - name: telegraf-conf
                       configMap:
                            name: telegraf-conf

