FROM	alpine:latest

RUN		apk update; apk add --no-cache wget \
										openrc \
										apache2; \
						wget phpMyAdmin-5.0.4-all-languages.tar.gz; \
						tar zxf phpMyAdmin-5.0.4-all-languages.tar.gz; \
						mv  phpMyAdmin-5.0.4-all-languages phpmmyadmin; \


