apiVersion: 1

providers:
    - name: 'default'
      orgId: 1
      folder: ''
      folderUid: ''
      type: file
      disableDeletion: false
      options:
          path: /grafana/conf/provisioning/dashboards/
