ALTER USER 'root'@'localhost' IDENTIFIED BY '$(ROOT_PASSWD)';
CREATE DATABASE $(WP_DATABASE);
CREATE USER '$(WP_USERNAME)'@'localhost' IDENTIFIED BY '$(WP_PASSWD)';
GRANT ALL PRIVILEGES ON $(WP_DATABASE).* TO '$(WP_USERNAME)'@'localhost';
FLUSH PRIVILEGES;
