apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: https://influxdb-svc:8086
    user: admin
    database: telegraf
    isDefault:
    secureJsonData:
      password: passwd
    version: 1
    editable: false
