apiVersion: v1
kind: Secret
metadata:
    name: mysql-credentials
type: Opaque
data:
    mysql_root_passwd: cGFzc3dk 
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-svc
    labels:
        app: mysql-svc
spec:
    ports:
        - port: 3306
          targetPort: 3306
          protocol: TCP
    selector:
        app: mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: local
    volume-svc: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Mi
  selector:
    matchLabels:
      type: local
      volume-svc: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    selector:
        matchLabels: 
            app: mysql
    replicas: 1 
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql:services
                  imagePullPolicy: Never
                  ports:
                      - protocol: TCP
                        containerPort: 3306
                  volumeMounts:
                      - name: mysql-volume
                        mountPath: /var/lib/mysql
                      - name: telegraf-conf
                        mountPath: /etc/telegraf/
                  env:
                      - name: PMA_USER
                        valueFrom:
                             secretKeyRef:
                                 name: pma-credentials
                                 key: pma_user
                      - name: PMA_PASSWD
                        valueFrom:
                             secretKeyRef:
                                 name: pma-credentials
                                 key: pma_passwd
                      - name: WP_ADMIN
                        valueFrom:
                                secretKeyRef:
                                    name: wp-credentials
                                    key: wp_admin
                      - name: WP_PASSWD
                        valueFrom:
                                secretKeyRef:
                                    name: wp-credentials
                                    key: wp_passwd
                      - name: MYSQL_ROOT_PASSWD
                        valueFrom:
                                secretKeyRef:
                                    name: mysql-credentials
                                    key: mysql_root_passwd
            volumes:
                - name: mysql-volume
                  persistentVolumeClaim:
                       claimName: mysql-volume-claim
                - name: telegraf-conf
                  configMap:
                       name: telegraf-conf
## env vars for mysql user - pw
