apiVersion: v1
kind: ConfigMap
metadata:
    name: telegraf-conf
data:
    telegraf.conf: |+
        [global_tags]
        [agent]
          interval = "10s"
          round_interval = true
          metric_batch_size = 1000
          metric_buffer_limit = 10000
          collection_jitter = "0s"
          flush_interval = "10s"
          flush_jitter = "0s"
          precision = ""
          hostname = ""
          omit_hostname = false
        [[outputs.influxdb]]
          urls = ["https://influxdb-svc.default.svc.cluster.local:8086"]
          database = ""
          username = "admin"
          password = "passwd"
          insecure_skip_verify = true
        [[inputs.cpu]]
          percpu = true
          totalcpu = true
          collect_cpu_time = false
          report_active = false
        [[inputs.mem]]
        [[inputs.docker]]
          endpoint = "unix://var/run/docker.sock"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: telegraf
    labels:
        app: telegraf
spec:
    replicas: 1
    selector:
        matchLabels:
            app: telegraf
    template:
        metadata:
            labels:
                app: telegraf
        spec:
            containers:
              - name: telegraf
                image: telegraf:latest
                imagePullPolicy: Never
                volumeMounts:
                   - name: telegraf-conf
                     mountPath: /etc/telegraf/
                     readOnly: true
                   - name: calcetin-docker
                     mountPath: /var/run/docker.sock
            volumes:
                   - name: telegraf-conf
                     configMap:
                        name: telegraf-conf
                   - name: calcetin-docker
                     hostPath: 
                        path: /var/run/docker.sock

