apiVersion: v1
kind: Secret
metadata:
    name: telegraf-secrets
type: Opaque
data:
    telegraf-db: dGVsZWdyYWY=
    telegraf-usr: dGVsZWdyYWY=
    telegraf-passwd: dGVsZWdyYWZwYXNzd2Q=
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: telegraf-conf
data:
    telegraf.conf: |+
        [global_tags]
        [agent]
          interval = "10s"
          round_interval = true
          metric_batch_size = 1000
          metric_buffer_limit = 10000
          collection_jitter = "0s"
          flush_interval = "10s"
          flush_jitter = "0s"
          precision = ""
          hostname = ""
          omit_hostname = false
        [[outputs.influxdb]]
          urls = ["https://influxdb-svc.default.svc.cluster.local:8086"]
          database = ""
          username = "telegraf"
          password = "telegrafpasswd"
          insecure_skip_verify = true
        [[inputs.cpu]]
          percpu = true
          totalcpu = true
          collect_cpu_time = false
          report_active = false
        [[inputs.mem]]
        [[inputs.docker]]
          endpoint = "unix://var/run/docker.sock"
        "$TEST"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: telegraf
    labels:
        app: telegraf
spec:
    replicas: 1
    selector:
        matchLabels:
            app: telegraf
    template:
        metadata:
            labels:
                app: telegraf
        spec:
            containers:
              - name: telegraf
                image: telegraf:latest
                imagePullPolicy: Never
                volumeMounts:
                   - name: telegraf-conf
                     mountPath: /etc/telegraf/
                     readOnly: true
                env:
                   - name: TEST
                     value: checa si parsea env vars a la hora de montar el config file
            volumes:
                   - name: telegraf-conf
                     configMap:
                        name: telegraf-conf
